# Generated by Django 4.2.4 on 2023-08-21 11:29

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(validators=[core.models.validate_datetime]),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(512, message='Events are currently limited to 512 participants max.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_end',
            field=models.DateTimeField(validators=[core.models.validate_datetime]),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_start',
            field=models.DateTimeField(validators=[core.models.validate_datetime]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(validators=[core.models.validate_datetime]),
        ),
    ]
