# Generated by Django 4.2.4 on 2023-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_require_confirmation_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.CharField(choices=[('signup/form_base.html', 'Base')], default='signup/form_base.html', max_length=128),
        ),
    ]
