# Generated by Django 4.2.4 on 2023-08-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventupdate_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventupdate',
            name='type',
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='event_type',
            field=models.CharField(choices=[('joined', 'Joined'), ('left', 'Left')], default='joined', max_length=16),
        ),
    ]
