# Generated by Django 4.2.4 on 2023-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_eventupdate_type_eventupdate_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='event',
            name='details_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.CharField(choices=[('signup/form_base.html', 'Base'), ('signup/form_dark.html', 'Dark')], default='signup/form_base.html', max_length=128),
        ),
    ]
