# Generated by Django 4.2.4 on 2023-08-31 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_options_event_details_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventupdate',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.CharField(choices=[('signup/form_base.html', 'Base'), ('signup/form_dark.html', 'Dark'), ('signup/form_mild.html', 'Mild')], default='signup/form_base.html', max_length=128),
        ),
        migrations.AlterField(
            model_name='eventupdate',
            name='event_type',
            field=models.CharField(choices=[('joined', 'Joined'), ('left', 'Left'), ('kicked', 'Kicked')], default='joined', max_length=16),
        ),
        migrations.CreateModel(
            name='UserConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
