# Generated by Django 4.2.4 on 2023-08-31 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_eventupdate_options_user_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
